# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roger/Github

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roger/Github

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roger/Github/CMakeFiles /home/roger/Github/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roger/Github/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named algorithmhw

# Build rule for target.
algorithmhw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algorithmhw
.PHONY : algorithmhw

# fast build rule for target.
algorithmhw/fast:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/build
.PHONY : algorithmhw/fast

chapter1.o: chapter1.cpp.o
.PHONY : chapter1.o

# target to build an object file
chapter1.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter1.cpp.o
.PHONY : chapter1.cpp.o

chapter1.i: chapter1.cpp.i
.PHONY : chapter1.i

# target to preprocess a source file
chapter1.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter1.cpp.i
.PHONY : chapter1.cpp.i

chapter1.s: chapter1.cpp.s
.PHONY : chapter1.s

# target to generate assembly for a file
chapter1.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter1.cpp.s
.PHONY : chapter1.cpp.s

chapter2.o: chapter2.cpp.o
.PHONY : chapter2.o

# target to build an object file
chapter2.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter2.cpp.o
.PHONY : chapter2.cpp.o

chapter2.i: chapter2.cpp.i
.PHONY : chapter2.i

# target to preprocess a source file
chapter2.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter2.cpp.i
.PHONY : chapter2.cpp.i

chapter2.s: chapter2.cpp.s
.PHONY : chapter2.s

# target to generate assembly for a file
chapter2.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter2.cpp.s
.PHONY : chapter2.cpp.s

chapter4.o: chapter4.cpp.o
.PHONY : chapter4.o

# target to build an object file
chapter4.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter4.cpp.o
.PHONY : chapter4.cpp.o

chapter4.i: chapter4.cpp.i
.PHONY : chapter4.i

# target to preprocess a source file
chapter4.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter4.cpp.i
.PHONY : chapter4.cpp.i

chapter4.s: chapter4.cpp.s
.PHONY : chapter4.s

# target to generate assembly for a file
chapter4.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter4.cpp.s
.PHONY : chapter4.cpp.s

chapter5.o: chapter5.cpp.o
.PHONY : chapter5.o

# target to build an object file
chapter5.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter5.cpp.o
.PHONY : chapter5.cpp.o

chapter5.i: chapter5.cpp.i
.PHONY : chapter5.i

# target to preprocess a source file
chapter5.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter5.cpp.i
.PHONY : chapter5.cpp.i

chapter5.s: chapter5.cpp.s
.PHONY : chapter5.s

# target to generate assembly for a file
chapter5.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter5.cpp.s
.PHONY : chapter5.cpp.s

chapter6.o: chapter6.cpp.o
.PHONY : chapter6.o

# target to build an object file
chapter6.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter6.cpp.o
.PHONY : chapter6.cpp.o

chapter6.i: chapter6.cpp.i
.PHONY : chapter6.i

# target to preprocess a source file
chapter6.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter6.cpp.i
.PHONY : chapter6.cpp.i

chapter6.s: chapter6.cpp.s
.PHONY : chapter6.s

# target to generate assembly for a file
chapter6.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter6.cpp.s
.PHONY : chapter6.cpp.s

chapter7.o: chapter7.cpp.o
.PHONY : chapter7.o

# target to build an object file
chapter7.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter7.cpp.o
.PHONY : chapter7.cpp.o

chapter7.i: chapter7.cpp.i
.PHONY : chapter7.i

# target to preprocess a source file
chapter7.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter7.cpp.i
.PHONY : chapter7.cpp.i

chapter7.s: chapter7.cpp.s
.PHONY : chapter7.s

# target to generate assembly for a file
chapter7.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter7.cpp.s
.PHONY : chapter7.cpp.s

chapter8.o: chapter8.cpp.o
.PHONY : chapter8.o

# target to build an object file
chapter8.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter8.cpp.o
.PHONY : chapter8.cpp.o

chapter8.i: chapter8.cpp.i
.PHONY : chapter8.i

# target to preprocess a source file
chapter8.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter8.cpp.i
.PHONY : chapter8.cpp.i

chapter8.s: chapter8.cpp.s
.PHONY : chapter8.s

# target to generate assembly for a file
chapter8.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/chapter8.cpp.s
.PHONY : chapter8.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/algorithmhw.dir/build.make CMakeFiles/algorithmhw.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... algorithmhw"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chapter1.o"
	@echo "... chapter1.i"
	@echo "... chapter1.s"
	@echo "... chapter2.o"
	@echo "... chapter2.i"
	@echo "... chapter2.s"
	@echo "... chapter4.o"
	@echo "... chapter4.i"
	@echo "... chapter4.s"
	@echo "... chapter5.o"
	@echo "... chapter5.i"
	@echo "... chapter5.s"
	@echo "... chapter6.o"
	@echo "... chapter6.i"
	@echo "... chapter6.s"
	@echo "... chapter7.o"
	@echo "... chapter7.i"
	@echo "... chapter7.s"
	@echo "... chapter8.o"
	@echo "... chapter8.i"
	@echo "... chapter8.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

